# Generated by Django 3.2.11 on 2022-01-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.TextField(),
        ),
    ]
